"""Renders grounded steps into the SKILL.md (plus generated scripts) that is
this pipeline's actual deliverable, per ARCHITECTURE.md §Stage 5: YAML
frontmatter (name, description / when to use, required inputs), the ordered
step list, and a verification section.

Two things this file is deliberately careful about:

1. **Flagged steps are marked, never silently included.** ARCHITECTURE.md is
   explicit that a framework which knows what it doesn't know is more
   trustworthy than one that's silently wrong sometimes. On real sessions
   the flagged proportion is very high (92% across the five recordings in
   this repo, almost entirely Stage 4 passthrough), so the document leads
   with a reliability summary instead of burying that per step.
2. **No YAML dependency.** The project has no yaml library in its
   dependencies and doesn't need one to emit a handful of scalars, so
   frontmatter values are emitted as single-quoted YAML scalars with
   internal quotes doubled — the standard YAML escape, and the only one
   needed for the strings involved here.
"""

from __future__ import annotations

import re
from collections import Counter

from .schema import GroundedStep

SKILL_DIR_NAME = "skill"
SCRIPTS_DIR_NAME = "scripts"

# Words that carry no identifying signal in a VLM-written target description
# — generic UI furniture, verbs, and articles. Removing them leaves the words
# that actually distinguish one recorded workflow from another (app names,
# specific surfaces), which is what the auto-derived skill name is built from.
_NAME_STOPWORDS = frozenset([
    "a", "an", "and", "at", "bar", "box", "by", "clicked", "clicking", "click", "content",
    "contents", "current", "display", "e.g", "element", "entry", "field", "first", "for",
    "from", "icon", "in", "interface", "into", "item", "items", "its", "list", "main", "menu",
    "new", "of", "on", "onto", "open", "opened", "option", "options", "page", "panel", "pane",
    "region", "row", "screen", "scrollbar", "second", "section", "select", "selected",
    "specific", "such", "the", "their", "them", "then", "this", "to", "toolbar", "top", "user",
    "various", "view", "viewing", "window", "with", "within", "button", "area", "application",
    "app", "file", "files", "folder", "folders", "link", "links", "text", "value", "where",
    "which", "while", "who", "whose", "after", "before", "during"
])

_SLUG_SPLIT = re.compile(r"[^a-z0-9]+")


def _slugify(text: str, max_words: int = 6) -> str:
    words = [w for w in _SLUG_SPLIT.split(text.lower()) if w]
    return "-".join(words[:max_words]) or "step"


def derive_skill_name(steps: list[GroundedStep], session_id: str) -> str:
    """A best-effort slug from the most distinctive words in the step targets.

    A heuristic, and labelled as one in the emitted document — the operator
    is expected to rename it. It exists so the output is always valid without
    a model call; ``--name`` overrides it.
    """
    counts: Counter[str] = Counter()
    for step in steps:
        target = step.ui_target.description if step.ui_target else step.intent
        for word in _SLUG_SPLIT.split(target.lower()):
            if len(word) > 2 and word not in _NAME_STOPWORDS and not word.isdigit():
                counts[word] += 1
    top = [word for word, _ in counts.most_common(2)]
    if not top:
        return f"workflow-{session_id[:8]}"
    return "-".join(top) + "-workflow"


def _yaml_scalar(value: str) -> str:
    """A single-quoted YAML scalar, with internal single quotes doubled."""
    return "'" + value.replace("\n", " ").replace("'", "''").strip() + "'"


def _yaml_list(values: list[str]) -> str:
    """A YAML sequence, as either an inline empty list or an indented block.

    Includes its own leading separator (a space or a newline) so the caller
    never emits a trailing space before a block list.
    """
    if not values:
        return " []"
    return "\n" + "\n".join(f"  - {_yaml_scalar(v)}" for v in values)


def required_inputs(steps: list[GroundedStep]) -> list[str]:
    """The union of every parameter Stage 4 judged to be a variable input,
    in first-seen order — these are what the skill should expose as
    parameters rather than hard-coding from this one recording."""
    seen: list[str] = []
    for step in steps:
        for name in step.variable_parameters:
            if name not in seen:
                seen.append(name)
    return seen


def script_filename(step: GroundedStep, index: int) -> str:
    return f"step-{index:04d}-{_slugify(step.intent, max_words=5)}.sh"


def render_script(step: GroundedStep) -> str:
    """A standalone shell script for one scripted step.

    ``set -eu`` so a failure stops rather than silently continuing into the
    next step of a replay.
    """
    return (
        "#!/bin/sh\n"
        "# Generated by prentice Stage 5 (Ground & output).\n"
        f"# Intent: {step.intent}\n"
        f"# Traces back to Stage 3 step(s): {', '.join(step.source_step_ids)}\n"
        "# Review before running — this command was derived from values a\n"
        "# vision model extracted from a screen recording, not from a\n"
        "# human-authored script.\n"
        "set -eu\n"
        f"{step.script}\n"
    )


def _reliability_summary(steps: list[GroundedStep]) -> str:
    total = len(steps)
    if total == 0:
        return "This skill contains no steps.\n"
    scripted = sum(1 for s in steps if s.grounding == "script")
    ax_grounded = sum(1 for s in steps if s.ui_target and s.ui_target.has_ax_identifier)
    passthrough = sum(1 for s in steps if s.confidence == "unrefined_passthrough")
    flagged = sum(1 for s in steps if s.needs_review)
    inferred = sum(1 for s in steps if s.source == "inferred")

    def pct(n: int) -> str:
        return f"{n} of {total} ({n / total:.0%})"

    lines = [
        "| Property | Value | Why it matters |",
        "| --- | --- | --- |",
        f"| Scripted steps | {pct(scripted)} | Execute directly; immune to UI-grounding failure. |",
        f"| UI-replay steps | {pct(total - scripted)} | Must be re-grounded in the live UI at replay time. |",
        f"| With accessibility identifier | {pct(ax_grounded)} | The strongest UI-replay signal available. |",
        f"| Flagged `needs-review` | {pct(flagged)} | Not verified; read before trusting. |",
        f"| Never refined (Stage 4 passthrough) | {pct(passthrough)} | Stage 4 could not process these at all. |",
        f"| From vision only (no event log) | {pct(inferred)} | Inferred from pixels; weaker than a logged event. |",
    ]
    return "\n".join(lines) + "\n"


def _render_step(step: GroundedStep, number: int) -> str:
    badges = []
    if step.needs_review:
        badges.append("**needs-review**")
    if step.source == "inferred":
        badges.append("_vision-only_")
    badge_text = f" — {', '.join(badges)}" if badges else ""

    lines = [f"### {number}. {step.intent or '(no intent recorded)'}{badge_text}", ""]
    lines.append(f"- **Action:** `{step.action_type}`")

    if step.grounding == "script":
        lines.append(f"- **Replay by running:** `{SCRIPTS_DIR_NAME}/{step.script_path}`")
        lines.append("")
        lines.append("  ```sh")
        lines.append(f"  {step.script}")
        lines.append("  ```")
    else:
        target = step.ui_target
        assert target is not None  # guaranteed by GroundedStep construction
        lines.append(f"- **Replay by locating:** {target.description or '(no target recorded)'}")
        if target.has_ax_identifier:
            ax_parts = [
                f"{label}={value!r}"
                for label, value in (
                    ("role", target.ax_role),
                    ("title", target.ax_title),
                    ("description", target.ax_description),
                    ("value", target.ax_value),
                )
                if value
            ]
            lines.append(f"- **Accessibility identifier:** {', '.join(ax_parts)}")
        if target.fallback_x is not None and target.fallback_y is not None:
            lines.append(
                f"- **Fallback coordinates:** ({target.fallback_x:.0f}, {target.fallback_y:.0f}) "
                "— last resort only; re-ground from the description above first."
            )

    if step.parameters:
        rendered = ", ".join(f"`{k}` = `{v!r}`" for k, v in step.parameters.items())
        lines.append(f"- **Parameters:** {rendered}")
    if step.variable_parameters:
        lines.append(f"- **Variable inputs:** {', '.join(f'`{v}`' for v in step.variable_parameters)}")
    if step.needs_review and step.review_reason:
        lines.append(f"- **Review reason:** {step.review_reason}")

    lines.append(f"- **Traces to:** {', '.join(f'`{s}`' for s in step.source_step_ids)}")
    return "\n".join(lines) + "\n"


def _verification_section(steps: list[GroundedStep]) -> str:
    flagged = sum(1 for s in steps if s.needs_review)
    final_intent = next((s.intent for s in reversed(steps) if s.intent), None)

    lines = ["## Verification", ""]
    lines.append("After replaying this skill, confirm:")
    lines.append("")
    if final_intent:
        lines.append(f"1. The end state matches the recording's final step: {final_intent}")
    else:
        lines.append("1. The end state matches the recorded workflow's final step.")
    lines.append("2. No step was skipped because its UI target could not be found.")
    if flagged:
        lines.append(
            f"3. Each of the {flagged} `needs-review` step(s) above did what its intent claims — "
            "these were not verified by the pipeline."
        )
    lines.append("")
    lines.append(
        "This pipeline has no automated replay-success measurement yet "
        "(`ARCHITECTURE.md` §3), so this section is a human checklist, not a test."
    )
    return "\n".join(lines) + "\n"


def render_skill_md(
    steps: list[GroundedStep], *, skill_name: str, description: str, session_id: str
) -> str:
    inputs = required_inputs(steps)
    parts = [
        "---",
        f"name: {_yaml_scalar(skill_name)}",
        f"description: {_yaml_scalar(description)}",
        f"required_inputs:{_yaml_list(inputs)}",
        "---",
        "",
        f"# {skill_name}",
        "",
        "> Auto-generated by prentice Stage 5 (Ground & output) from a screen recording.",
        "> Every step below was derived by machine, without human annotation — the name and",
        "> description are heuristics, and nothing here has been verified against a successful",
        "> replay. **Read the reliability summary before executing any of it.**",
        "",
        "## Reliability summary",
        "",
        _reliability_summary(steps),
        "## Required inputs",
        "",
    ]

    if inputs:
        parts.append(
            "These values were recorded as variable rather than fixed, and should be supplied "
            "per run:"
        )
        parts.append("")
        parts.extend(f"- `{name}`" for name in inputs)
    else:
        parts.append(
            "None identified. Every recorded value was treated as fixed to this recording, so "
            "the skill will replay it verbatim — check the steps below for values that should "
            "really be parameters."
        )
    parts.append("")

    parts.append("## Steps")
    parts.append("")
    if steps:
        parts.extend(_render_step(step, i + 1) for i, step in enumerate(steps))
    else:
        parts.append("No steps were produced for this recording.")
        parts.append("")

    parts.append(_verification_section(steps))
    parts.append("## Provenance")
    parts.append("")
    parts.append(
        f"Generated from session `{session_id}`. Each step's **Traces to** line gives the "
        "Stage 3 step id(s) it came from, so any claim here can be checked against "
        "`steps.jsonl`, `segments.jsonl`, and the retained keyframes in that session directory."
    )
    parts.append("")
    parts.append(
        "Known limitations inherited from the pipeline (`ARCHITECTURE.md` §5): no control-flow "
        "inference (loops or conditionals), no disambiguation of near-identical UI elements, "
        "imprecise drag and text-selection boundaries, and no generalization beyond this single "
        "demonstration."
    )
    return "\n".join(parts) + "\n"
